[
  "In the age of the internet, there's no such thing as a private debate.",
  "But is that bad for science? Some scientists have had concerns.",
  "When debates in any sector move beyond the halls of universities and government agencies, there's potential for information to be used incorrectly, leading to public confusion; yet, open debate can also promote communication between the scientific community and the public.",
  "Recent open debates on scientific research, health, and policy have aroused greater public attention and encouraged more diverse voices.",
  "If this trend spurs scientists to agree more quickly about the best solutions to our problems—and <em>at the same time</em> helps the public observe the process of scientific discourse more clearly—then this is good for everyone, including scientists.",
  "<br></br>",
  "A recent debate published in The New York Times discussed the question of how quickly medicine should be developed and produced.",
  "Issues <em>such as</em> safety of the product and perception of the public were examined and considered.",
  "But some experts worried that such public speculation might lead people to believe that disagreement about the details meant a <em>lack of</em> adequate scientific consensus over the safety and efficiency of modern-day medicine.",
  "",
  "<br></br>",
  "The anxiety seems misplaced.",
  "Gone are the days of going to a conference and debating scientific issues, and that's good because those gatherings were not diverse enough and excluded many important voices.",
  "These days, the public can access debates about science <em>regardless of</em> where they <em>take place</em>.",
  "",
  "<br></br>",
  "For many scientists, public debate is a new frontier and it may <em>feel like</em> a place with few restraints or rules, but <em>rather than</em> avoiding such conversations, let the debates be transparent and vigorous, wherever they are held.",
  "If the public is to understand that science is an honorably self-correcting process, the idea that science is a fixed set of facts in a textbook needs to be dismissed.",
  "With the validity of science coming <em>under attack</em>, there's a need for scientific debates to be perceived as open and true to life.",
  "Let everyone see the noisy, messy deliberations that advance science and lead to decisions that benefit us all.",
  "",
  "<br></br>",
  "",
  "<br></br>",
];
